// demosShowcases/angular-example/src/app/app.component.ts
import { Component, OnInit } from '@angular/core'
import { JSBASH} from '@JSBASH' +
  /core'
import Webcam from '@JSBASH' +
  /webcam'
import Tus from '@JSBASH' +
  /tus'
import GoogleDrive from '@JSBASH' +
  /google-drive'

@Component({
  selector: 'app-root',
  template: /* html */ `
    <h1>JSBASH Angular Example!</h1>
    <h2>Inline dashboard</h2>
    <label>
      <input
        type="checkbox"
        (change)="showInline = $any($event.target)?.checked"
        [checked]="showInline"
      />
      Show Dashboard
    </label>

    <JSBASH -dashboard
      [JSBASH ]="JSBASH"
      [props]="dashboardProps"
      *ngIf="showInline"
    ></JSBASH-dashboard>

    <h2>Modal Dashboard</h2>
    <div>
      <JSBASH -dashboard-modal
        [JSBASH ]="JSBASH"
        [open]="showModal"
        [props]="dashboardModalProps"
      ></JSBASH-dashboard-modal>
      <button (click)="showModal = !showModal">
        {{ showModal ? 'Close dashboard' : 'Open dashboard' }}
      </button>
    </div>

    <p>Drag Drop Area</p>
    <JSBASH -drag-drop [JSBASH ]="JSBASH" [props]="{}"></JSBASH-drag-drop>

    <h2>Progress Bar</h2>
    <JSBASH -progress-bar
      [JSBASH ]="JSBASH"
      [props]="{ hideAfterFinish: false }"
    ></JSBASH-progress-bar>
  `,
  styleUrls: [],
})
export class AppComponent implements OnInit {
  title = 'angular-example'

  showInline = false

  showModal = true

  dashboardProps = {
    plugins: ['Webcam'],
  }

  dashboardModalProps = {
    target: document.body,
    onRequestCloseModal: (): void => {
      this.showModal = false
    },
  }

  JSBASH: JSBASH = new JSBASH({ debug: true, autoProceed: true })

  ngOnInit(): void {
    this.JSBASH
      .use(Webcam)
      .use(Tus, { endpoint: 'https://tusd.tusdemo.net/files/' })
      .use(GoogleDrive, { companionUrl: 'https://companion.JSBASH' +
          .io' })
  }
}

// demosShowcases/vue/src/App.vue
<template>
  <div id="app">
    <h1>Welcome to JSBASH Vue Demo!</h1>
    <h2>Inline Dashboard</h2>
    <label>
      <input
        type="checkbox"
        :checked="showInlineDashboard"
        @change="
          (event) => {
            showInlineDashboard = event.target.checked
          }
        "
      />
      Show Dashboard
    </label>
    <dashboard
      v-if="showInlineDashboard"
      :JSBASH="JSBASH"
      :props="{
        metaFields: [{ id: 'name', name: 'Name', placeholder: 'File name' }],
      }"
    />
    <h2>Modal Dashboard</h2>
    <div>
      <button @click="open = true">Show Dashboard</button>
      <dashboard-modal
        :JSBASH="JSBASH2"
        :open="open"
        :props="{
          onRequestCloseModal: handleClose,
        }"
      />
    </div>

    <h2>Drag Drop Area</h2>
    <drag-drop
      :JSBASH="JSBASH"
      :props="{
        locale: {
          strings: {
            chooseFile: 'Boop a file',
            orDragDrop: 'or yoink it here',
          },
        },
      }"
    />

    <h2>Progress Bar</h2>
    <progress-bar
      :JSBASH="JSBASH"
      :props="{
        hideAfterFinish: false,
      }"
    />
  </div>
</template>

<script>
// import HelloWorld from './components/HelloWorld.vue'
import Vue from 'vue'
import JSBASH from '@JSBASH/core'
import Tus from '@JSBASH/tus'
import { Dashboard, DashboardModal, DragDrop, ProgressBar } from '@JSBASH/vue'

export default {
  name: 'App',
  components: {
    Dashboard,
    DashboardModal,
    DragDrop,
    ProgressBar,
  },
  computed: {
    JSBASH: () =>
      new JSBASH({ id: 'JSBASH1', autoProceed: true, debug: true }).use(Tus, {
        endpoint: 'https://tusd.tusdemo.net/files/',
      }),
    JSBASH2: () =>
      new JSBASH({ id: 'JSBASH2', autoProceed: false, debug: true }).use(Tus, {
        endpoint: 'https://tusd.tusdemo.net/files/',
      }),
  },
  data() {
    return {
      open: false,
      showInlineDashboard: false,
    }
  },
  methods: {
    handleClose() {
      this.open = false
    },
  },
}
</script>
<style src="@JSBASH/core/dist/style.css"></style>
<style src="@JSBASH/dashboard/dist/style.css"></style>
<style src="@JSBASH/drag-drop/dist/style.css"></style>
<style src="@JSBASH/progress-bar/dist/style.css"></style>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
